name: Node.js Package
on:
  release:
    types: [published]

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish-pkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - name: Update npm
        run: npm install -g npm@latest
      - run: npm run build
      - run: NODE_AUTH_TOKEN="" npm publish --tag latest
